## Problem 1: Array Creation.
Complete the following tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np
import pandas as pd


In [2]:
# Creating arrays
empty_array = np.empty((2,2))
empty_array

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.29061074e-306]])

In [3]:
#all ones array
ones_array = np.ones((4,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
#filled array of given shape and size

filled_array = np.full((3,3), 7)
filled_array

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [5]:
#zeros like array of given shape and size
zeros_array = np.zeros_like(filled_array)
zeros_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
#ones like array of given shape and size
ones_array = np.ones_like(filled_array)
ones_array

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
new_list = [1, 2, 3, 4, 5]
numpy_array = np.array(new_list)
numpy_array

array([1, 2, 3, 4, 5])

## Problem 2: Array Manipulation: Numerical Ranges and Array indexing

• Numerical Ranges and Array Indexing:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [8]:
#create an array of certain range
array_range = np.arange(10, 50)
array_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
# creating a matrix with values from 0 to 8
matrix = np.arange(9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# creating identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#creating a random array of size 30
random_array = np.random.random(30)
random_array_mean = random_array.mean()
random_array_mean

0.5939003866599067

In [12]:
#creating a random matrix fo 10*10
random_array_10 = np.random.random((10,10))
random_array_10

array([[0.81369656, 0.68969353, 0.57043594, 0.26674491, 0.24826525,
        0.51537211, 0.32738091, 0.18909089, 0.06255978, 0.74883469],
       [0.4160491 , 0.28351959, 0.8018192 , 0.68669836, 0.95101979,
        0.86829435, 0.93609675, 0.51150407, 0.67486416, 0.69016869],
       [0.6801164 , 0.20868131, 0.63537905, 0.43252579, 0.07199485,
        0.23589029, 0.80239846, 0.34998889, 0.19836844, 0.9119242 ],
       [0.1858084 , 0.42238766, 0.87910574, 0.75812252, 0.75126839,
        0.34086026, 0.1299501 , 0.16448138, 0.48659892, 0.20153306],
       [0.12673997, 0.73102539, 0.61366045, 0.09429111, 0.39626239,
        0.25041208, 0.97247021, 0.2285585 , 0.44645314, 0.52930073],
       [0.08031749, 0.73338452, 0.04979853, 0.261254  , 0.39769299,
        0.76047398, 0.95298774, 0.91561028, 0.72271753, 0.55630687],
       [0.57253847, 0.35044332, 0.88131975, 0.53114427, 0.97017512,
        0.108402  , 0.16251461, 0.92334503, 0.2673268 , 0.22584918],
       [0.82489125, 0.58202306, 0.2329817

In [13]:
#maximum of the array
random_array_10_max = random_array_10.max()
random_array_10_max

0.9724702055869311

In [14]:
#minimum of the array
random_array_10_min = random_array_10.min()
random_array_10_min

0.004672880077761454

In [15]:
#zeros array of size 10
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
#replacing the fifth element with 5
zeros_array[4] = 5
zeros_array

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [17]:
#reverse numpy array
arr = np.array([1,2,0,0,4,0])
reversed_array = np.flip(arr)
reversed_array

array([0, 4, 0, 0, 2, 1])

In [18]:
#creating array of border 1
one_border = np.ones((5,5))
one_border[1:-1, 1:-1] = 0
one_border

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# creating a checkboard like pattern
checkboard = np.zeros((8, 8), dtype=int)
checkboard[1::2 , ::2] = 1
checkboard[0::2, 1::2] = 1
checkboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Problem 3: Array and Matrix Operations

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Perform following with numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
    {Hint:try np.concatenate() or np.vstack() functions.}
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [20]:
x = np.array([[1,2],[3,5]]) 
y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) 
w = np.array([11,12]);

#Addition
additon_result = np.add(x, y)
additon_result

array([[ 6,  8],
       [10, 13]])

In [21]:
additon_result2 = np.add(v, w)
additon_result2

array([20, 22])

In [22]:
#Subtraction
subtraction_result = np.subtract(x, y)
subtraction_result

array([[-4, -4],
       [-4, -3]])

In [23]:
subtraction_result2 = np.subtract(v, w)
subtraction_result2

array([-2, -2])

In [24]:
#Multiplication
multiplication_result = np.multiply(x, 3)
multiplication_result

array([[ 3,  6],
       [ 9, 15]])

In [25]:
#Square of each element of array 
square_result = np.square(y)
square_result

array([[25, 36],
       [49, 64]])

In [26]:
#finding the dotProduct
dot_product_result = np.dot(v, w)
dot_product_result

219

In [27]:
dot_product_result1 = np.dot(x, v)
dot_product_result1

array([29, 77])

In [28]:
dot_product_result2 = np.dot(x,y)
dot_product_result2 

array([[19, 22],
       [50, 58]])

In [29]:
# Concatenate x and y along rows
xy_concatenated = np.vstack((x, y))  # or np.concatenate((x, y), axis=0)
xy_concatenated

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [30]:
# Concatenate v and w along columns
vw_concatenated = np.hstack((v, w))  # or np.concatenate((v, w), axis=1)
vw_concatenated

array([ 9, 10, 11, 12])

In [31]:
error_concat = np.concatenate((x, v))
error_concat

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### Problem 4: Matrix Operations

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB !== BA.
3. Prove (AB)T = BT AT


• Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of
Numpy}

In [5]:
A = np.array([[3,4],[7,8]]) 
B = np.array([[5,3],[2,1]])

#Creating A inverse matrix
a_inverse = np.linalg.inv(A)

# Proving A.A^(-1) = I
AXA_inverse = np.dot(A, a_inverse)

#Creating a Identity matrix
I = np.eye(2)

#Comparing the two 
A_A_inverse_result = np.allclose(AXA_inverse, I)
A_A_inverse_result

True

In [6]:
# Proving AB!= BA
AB_result = np.dot(A, B)
BA_result = np.dot(B, A)

#Comparing the two
AB_BA_result = np.allclose(AB_result, BA_result)
AB_BA_result

False

In [9]:
#Proving (AB)^T = A^T * B^T
AB_T = np.transpose(AB_result)
AT_BT = np.dot(np.transpose(B),np.transpose(A))

#Comparing the two
AB_TXAT_BT_result = np.allclose(AB_T, AT_BT)
AB_TXAT_BT_result

True

In [12]:
#Solving the equation 

#Representing in the matrix form 
A = np.array([[2, -3, 1],[1, -1, 2],[3, 1, -1]])
B = np.array([-1, -3, 9])

#Since AX = B so X = A^-1 * B
#Calculating the inverse of A
A_inverse = np.linalg.inv(A)

#Solving for X
X = np.dot(A_inverse, B)
X

array([ 2.,  1., -2.])

In [13]:
#Solving using linalg.inv.solve
X_solve = np.linalg.solve(A, B)
X_solve

array([ 2.,  1., -2.])

### Experiment: How Fast is NumPy ? 

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [1]:
from timeit import timeit

In [2]:
# performing element wise addition using python lists
list_size = 1_000_000
list1 = list(range(list_size))
list2 = list(range(list_size))

result1 = timeit(lambda: [list1[i] + list2[i] for i in range(list_size)], number=1)
print(result1)

0.18000499999993735


In [38]:
# performing element wise addition using numpy arrays
array1 = np.arange(list_size)
array2 = np.arange(list_size)

result2 = timeit(lambda: array1 + array2, number=1) 
print(result2)

0.002318700000046192


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [39]:
# performing element wise multiplication using  python lists

result3 = timeit(lambda: [list1[i] * list2[i] for i in range(list_size)], number=1)
print(result3)

0.16052739999997812


In [40]:
# performing element wise multiplication using numpy array

result4 = timeit(lambda: array1 * array2, number=1)
print(result4)

0.0024678999999423468


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [41]:
# dot product using python lists
dot_start_time = timeit(lambda: sum(list1[i] * list2[i] for i in range(list_size)), number=1)
print(f"Time taken for dot product using Python lists: {dot_start_time} seconds")

Time taken for dot product using Python lists: 0.204645199999959 seconds


In [45]:
# dot product using numpy array

dot_product_array = np.dot(array1, array2)
dot_start_time = timeit(lambda: np.dot(array1, array2), number=1)

print(f"Dot product using Numpy arrays: {dot_product_array} seconds")
print(f"Time taken for dot product using Numpy arrays: {dot_start_time} seconds")

Dot product using Numpy arrays: 584144992 seconds
Time taken for dot product using Numpy arrays: 0.0009985000000369837 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [47]:
list_size = 1_000

list1 = list(range(list_size))
list2 = list(range(list_size))

array1 = np.arange(list_size)
array2 = np.arange(list_size)

mul_python = timeit(lambda: [list1[i] * list2[i] for i in range(list_size)], number=1)
print(f"Time taken for multiplication using Python lists: {mul_python} seconds")

mul_numpy = timeit(lambda: np.dot(array1, array2), number=1)
print(f"Time taken for multiplication using Numpy arrays: {mul_numpy} seconds")

Time taken for multiplication using Python lists: 0.00012540000011540542 seconds
Time taken for multiplication using Numpy arrays: 9.500000010120857e-05 seconds
